"""rename department

Revision ID: 45db6c64f3d1
Revises: e9c276c80402
Create Date: 2024-04-04 15:42:35.281740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45db6c64f3d1'
down_revision = 'e9c276c80402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
